name: Build and deploy to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - { image_name: ubuntu1804-build, dockerfile: vowpal_wabbit/ubuntu1804-build.Dockerfile, context: ./ }
        - { image_name: ubuntu2004-build, dockerfile: vowpal_wabbit/ubuntu2004-build.Dockerfile, context: ./ }
        - { image_name: centos7_6_1810-build, dockerfile: vowpal_wabbit/centos7_6_1810-build.Dockerfile, context: ./ }
        - { image_name: manylinux2010-build, dockerfile: manylinux2010-build.Dockerfile, context: ./vowpal_wabbit/manylinux/ }
        - { image_name: manylinux2014_aarch64-build, dockerfile: manylinux2014_aarch64-build.Dockerfile, context: ./vowpal_wabbit/manylinux/ }
        - { image_name: rl-manylinux2010-build, dockerfile: rl-manylinux2010-build.Dockerfile, context: ./reinforcement_learning/manylinux-2010/ }
        - { image_name: rl-ubuntu-1804, dockerfile: reinforcement_learning/ubuntu1804-build.Dockerfile, context: ./}
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        if: ${{ matrix.config.image_name == 'manylinux2014_aarch64-build' }}
        uses: docker/setup-qemu-action@v1
      - name: Login, build and push image
        if: success()
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: "vowpalwabbit/${{matrix.config.image_name}}"
          dockerfile: "${{matrix.config.dockerfile}}"
          context: "${{ matrix.config.context }}"
          push_image_and_stages: true
