name:  Manual build and deploy Learning Loop to DockerHub

on:
  workflow_dispatch:
  
jobs:
  build:
    name: learning-loop-ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - { image_name: learning-loop, dockerfile: ubuntu-build.dockerfile, context: ./learning-loop/ }
    steps:
      - uses: actions/checkout@v3
      - name: Login, build and push image
        if: success()
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: "vowpalwabbit/${{matrix.config.image_name}}"
          dockerfile: "${{matrix.config.dockerfile}}"
          context: "${{ matrix.config.context }}"
          push_image_and_stages: true
