name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - { image_name: ubuntu1804-build, dockerfile: vowpal_wabbit/ubuntu1804-build.Dockerfile, context: ./ }
        - { image_name: centos7_6_1810-build, dockerfile: vowpal_wabbit/centos7_6_1810-build.Dockerfile, context: ./ }
        - { image_name: manylinux2010-build, dockerfile: manylinux2010-build.Dockerfile, context: ./vowpal_wabbit/manylinux-2010/ }
        - { image_name: rl-ubuntu-1604, dockerfile: reinforcement_learning/ubuntu1604-build.Dockerfile, context: ./}
        - { image_name: all-dev-ubuntu1604, dockerfile: development/ubuntu1604-dev.Dockerfile, context: ./ }
        - { image_name: vw-rel-alpine, dockerfile: vowpal_wabbit/vw-rel-alpine.Dockerfile, context: ./ }
    steps:
      - uses: actions/checkout@master
      - name: Build image
        if: success()
        uses: whoan/docker-build-with-cache-action@v4
        with:
          image_name: "vowpalwabbit/${{matrix.config.image_name}}"
          dockerfile: "${{matrix.config.dockerfile}}"
          context: "${{matrix.config.context}}"
          push_image_and_stages: false
