name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - { image_name: ubuntu1604-build, dockerfile: vowpal_wabbit/ubuntu1604-build.Dockerfile }
        - { image_name: ubuntu1404-build, dockerfile: vowpal_wabbit/ubuntu1404-build.Dockerfile }
        - { image_name: centos7_6_1810-build, dockerfile: vowpal_wabbit/centos7_6_1810-build.Dockerfile }
        - { image_name: manylinux2010-build, dockerfile: vowpal_wabbit/manylinux-2010/manylinux2010-build.Dockerfile }
        - { image_name: rl-ubuntu-1604, dockerfile: reinforcement_learning/ubuntu1604-build.Dockerfile}
        - { image_name: all-dev-ubuntu1604, dockerfile: development/ubuntu1604-dev.Dockerfile }
        - { image_name: vw-rel-alpine, dockerfile: vowpal_wabbit/vw-rel-alpine.Dockerfile }
    steps:
      - uses: actions/checkout@master
      - name: Build image
        if: success()
        uses: whoan/docker-build-with-cache-action@v4
        with:
          image_name: "vowpalwabbit/${{matrix.config.image_name}}"
          dockerfile: "${{matrix.config.dockerfile}}"
          push_image_and_stages: false
